title: pdrift
baseURL: /
params:
  layout_style: default
  palette: blue
  header:
    title: pdrift
    tagline: product parenting
    profile_img: /images/tt.jpeg
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
